name = "JLGame"
uuid = "736c1586-5226-4b2e-9818-fad6972f0408"
authors = ["Cameron Kirk"]
version = "1.0.0-DEV"

[compat]
julia = "1"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
