name = "SDLCanvas"
uuid = "736c1586-5226-4b2e-9818-fad6972f0408"
authors = ["Cameron Kirk"]
version = "1.12.6"

[deps]
SimpleDirectMediaLayer = "98e33af6-2ee5-5afd-9e75-cbc738b767c4"

[compat]
julia = "1"
SimpleDirectMediaLayer = "0.3, 0.4"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
